[project]
name = "nnet"
version = "0.0.1"
description = "Miniature version of torch like neural network training framework"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]